from django.test import TestCase
from balance.models import BaRegistroPago
# Create your tests here.
BaRegistroPago.objects.create(fecha_pago='2024-02-01',deudor_id=23,detalle_pago='pago realizado en plazo pero cliente paga en efectivo')

BaRegistroPago.objects.create(fecha_pago='2023-07-23', deudor_id=8, detalle_pago='pago realizado en plazo pero cliente paga en efectivo')
BaRegistroPago.objects.create(fecha_pago='2024-01-19', deudor_id=10, detalle_pago='pago realizado en plazo pero cliente paga en efectivo')
BaRegistroPago.objects.create(fecha_pago='2023-04-16', deudor_id=25, detalle_pago='pago realizado en plazo pero cliente paga en efectivo')
BaRegistroPago.objects.create(fecha_pago='2023-03-16', deudor_id=15, detalle_pago='pago realizado en plazo pero cliente paga en efectivo')
BaRegistroPago.objects.create(fecha_pago='2023-10-23', deudor_id=24, detalle_pago='pago realizado en plazo pero cliente paga en efectivo')
BaRegistroPago.objects.create(fecha_pago='2023-03-10', deudor_id=7, detalle_pago='pago realizado en plazo pero cliente paga en efectivo')
BaRegistroPago.objects.create(fecha_pago='2023-05-16', deudor_id=19, detalle_pago='pago realizado en plazo pero cliente paga en efectivo')
BaRegistroPago.objects.create(fecha_pago='2023-05-12', deudor_id=16, detalle_pago='pago realizado en plazo pero cliente paga en efectivo')
BaRegistroPago.objects.create(fecha_pago='2023-12-05', deudor_id=19, detalle_pago='pago realizado en plazo pero cliente paga en efectivo')
BaRegistroPago.objects.create(fecha_pago='2023-04-19', deudor_id=27, detalle_pago='pago realizado en plazo pero cliente paga en efectivo')
BaRegistroPago.objects.create(fecha_pago='2023-09-04', deudor_id=24, detalle_pago='pago realizado en plazo pero cliente paga en efectivo')
BaRegistroPago.objects.create(fecha_pago='2023-05-22', deudor_id=26, detalle_pago='pago realizado en plazo pero cliente paga en efectivo')
BaRegistroPago.objects.create(fecha_pago='2023-12-09', deudor_id=22, detalle_pago='pago realizado en plazo pero cliente paga en efectivo')
BaRegistroPago.objects.create(fecha_pago='2024-01-06', deudor_id=20, detalle_pago='pago realizado en plazo pero cliente paga en efectivo')
BaRegistroPago.objects.create(fecha_pago='2023-11-20', deudor_id=8, detalle_pago='pago realizado en plazo pero cliente paga en efectivo')
BaRegistroPago.objects.create(fecha_pago='2023-03-10', deudor_id=3, detalle_pago='pago realizado en plazo pero cliente paga en efectivo')
BaRegistroPago.objects.create(fecha_pago='2023-09-29', deudor_id=26, detalle_pago='pago realizado en plazo pero cliente paga en efectivo')
BaRegistroPago.objects.create(fecha_pago='2023-08-14', deudor_id=25, detalle_pago='pago realizado en plazo pero cliente paga en efectivo')
BaRegistroPago.objects.create(fecha_pago='2023-10-29', deudor_id=3, detalle_pago='pago realizado en plazo pero cliente paga en efectivo')
BaRegistroPago.objects.create(fecha_pago='2023-04-10', deudor_id=3, detalle_pago='pago realizado en plazo pero cliente paga en efectivo')
BaRegistroPago.objects.create(fecha_pago='2024-01-20', deudor_id=22, detalle_pago='pago realizado en plazo pero cliente paga en efectivo')
BaRegistroPago.objects.create(fecha_pago='2023-06-10', deudor_id=3, detalle_pago='pago realizado en plazo pero cliente paga en efectivo')
BaRegistroPago.objects.create(fecha_pago='2023-03-29', deudor_id=22, detalle_pago='pago realizado en plazo pero cliente paga en efectivo')
BaRegistroPago.objects.create(fecha_pago='2023-05-26', deudor_id=9, detalle_pago='pago realizado en plazo pero cliente paga en efectivo')
BaRegistroPago.objects.create(fecha_pago='2023-03-29', deudor_id=17, detalle_pago='pago realizado en plazo pero cliente paga en efectivo')
BaRegistroPago.objects.create(fecha_pago='2023-11-08', deudor_id=25, detalle_pago='pago realizado en plazo pero cliente paga en efectivo')
BaRegistroPago.objects.create(fecha_pago='2023-06-26', deudor_id=9, detalle_pago='pago realizado en plazo pero cliente paga en efectivo')
BaRegistroPago.objects.create(fecha_pago='2023-07-16', deudor_id=3, detalle_pago='pago realizado en plazo pero cliente paga en efectivo')
