# Generated by Django 5.0.2 on 2024-03-02 02:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaRegistroPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pago', models.DateTimeField(null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('detalle_pago', models.TextField(max_length=500)),
                ('deudor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deudor_pago', to='cliente.clcliente')),
            ],
            options={
                'verbose_name': 'Registro de Pago',
                'verbose_name_plural': 'Registros de Pagos',
                'db_table': 'ba_registro_pago',
            },
        ),
    ]
