# Generated by Django 5.0.2 on 2024-03-02 03:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balance', '0001_initial'),
        ('cliente', '0002_alter_clcliente_options_alter_clcliente_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baregistropago',
            name='deudor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos_realizados', to='cliente.clcliente'),
        ),
    ]
