# Generated by Django 5.0.2 on 2024-03-07 02:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balance', '0002_alter_baregistropago_deudor'),
        ('cliente', '0003_alter_clcliente_rut'),
    ]

    operations = [
        migrations.AddField(
            model_name='baregistropago',
            name='acreedor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pagos_acreedor', to='cliente.clcliente'),
        ),
        migrations.AddField(
            model_name='baregistropago',
            name='pago_realizado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='baregistropago',
            name='deudor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos_adeudor', to='cliente.clcliente'),
        ),
    ]
