# Generated by Django 5.0.2 on 2024-03-11 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balance', '0003_baregistropago_acreedor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaCtaInterna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cta', models.CharField(max_length=150)),
                ('monto_cta', models.IntegerField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cuenta Interna',
                'verbose_name_plural': 'Cuentas Internas',
                'db_table': 'ba_cta_interna',
            },
        ),
    ]
